version: '3.7'

services:
 web:
  build: .
  command: python /news_api/manage.py runserver 0.0.0.0:8000
  environment:
   - "ENVIRONMENT=development"
   - "DJANGO_DEBUG=1"
  volumes:
   - .:/news_api
  ports:
  - 8000:8000
  depends_on:
  - db
 db:
  image: postgres:latest
  environment:
   POSTGRES_PASSWORD: postgres
   POSTGRES_USER: postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: