# Generated by Django 3.2 on 2021-04-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount_of_upvotes',
        ),
    ]
